WITH CTE AS 
(
    SELECT TO_TIMESTAMP(STARTTIME) STARTED_AT
        ,DATE(TO_TIMESTAMP(STARTTIME)) STARTED_AT_DATE
        ,HOUR(TO_TIMESTAMP(STARTTIME)) STARTED_AT_HOUR
        ,MONTH(TO_TIMESTAMP(STARTTIME)) STARTED_AT_MONTH
        ,{{get_day_type('STARTTIME')}} AS STARTED_AT_DAYTYPE
        ,{{get_season('STARTTIME')}} AS STARTED_AT_WEATHER
       FROM {{ source('snowflake_first_project', 'bike') }}
    WHERE STARTTIME != 'starttime'
)
SELECT * FROM CTE