WITH CTE AS 
(
    SELECT TO_TIMESTAMP(STARTED_AT) STARTED_AT
        ,DATE(TO_TIMESTAMP(STARTED_AT)) STARTED_AT_DATE
        ,HOUR(TO_TIMESTAMP(STARTED_AT)) STARTED_AT_HOUR
        ,MONTH(TO_TIMESTAMP(STARTED_AT)) STARTED_AT_MONTH
        ,{{get_day_type('STARTED_AT')}} AS STARTED_AT_DAYTYPE
        ,{{get_season('STARTED_AT')}} AS STARTED_AT_WEATHER
       FROM {{ source('snowflake_first_project', 'bike') }}
    WHERE STARTED_AT != 'started_at'
)
SELECT * FROM CTE